
import "./globals.css";



export const metadata = {
  title: "Zsmenu",
  description: "Generated by Zsmenu",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
